dist: trusty
language: clojure

services:
  - docker

stages:
  - build

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure:
jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/dda-managed-ide-standalone.jar > target/dda-managed-ide-standalone.jar.md5
        - # create docker image
        - docker build -t dda-managed-ide --file integration/docker/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-managed-ide-test --file integration/docker/test/Dockerfile .
      deploy:
        - provider: releases
          skip_cleanup: true
          overwrite: true
          draft: true
          on:
            tags: true
          api_key:
            secure:
          file:
            - target/dda-managed-ide-standalone.jar
            - target/dda-managed-ide-standalone.jar.md5
        - provider: script
          skip_cleanup: true
          on:
            tags: true
          script: bash integration/docker/publish.sh dda-managed-ide
